### ISSUE TITLE
Only works with Resque v1.7.1

### ISSUE THREAD

**Issue by lantins** [staugaard/resque-multi-job-forks#1]
Hey,

I'm in the need for exactly what your plugin provides!
Although I'm running Resque v1.10.0, not v1.7.1.
I can see in Resque v1.8.0 they depricated `process` and moved to using `perform`.

Any objection, if I make the changes for Resque >1.8.0?

Thanks
Luke

**Comment by grosser** [comment]
have a look at [my fork](http://github.com/grosser/resque-multi-job-forks)

**Comment by lantins** [comment]
I should of looked at the forks! Doh.

Already started to hack on my own changes, I've taken a slightly different path to yourself though.

I was also adding the ability to use a job or time limit per fork.
I kinda liked the look of the original version, and it for me, a job limit is more suitable.

But now (after writing the above) I see there is samgranieri/resque-jobs-per-fork.

I'm tempted to finish what I've started for kicks...

**Comment by lantins** [comment]
Pull request sent, closing this issue, please see #2
