### ISSUE TITLE
Help testing against edge resque

### ISSUE THREAD

**Issue by steveklabnik** [staugaard/resque-multi-job-forks#11]
Hey there! 

I'm gearing up to work on Resque 2.0, and I'd like to coordinate better with plugin authors to make sure stuff doesn't break.

I'd like to know a few things:
1. Can I do something to help get you testing against edge Resque?
2. Are you monkey-patching anything in Resque currently? Can 2.0 expose an API to help you not have to do that any more?
3. Do you need any help in bringing your plugin up-to-date with the latest Resque?

Thanks!

Related: https://github.com/defunkt/resque/issues/880

**Comment by stulentsev** [comment]
@steveklabnik sorry, totally missed this one. I myself don't use this anymore, but I can give it a bit of attention if this is still actual.

**Comment by steveklabnik** [comment]
@stulentsev it's all good. Resque 2.0 is now cancelled, so it's not really a thing any longer.
