### ISSUE TITLE
Doesn't work with the latest resque version

### ISSUE THREAD

**Issue by adamcooper** [staugaard/resque-multi-job-forks#3]
I saw this plugin and would have used except it didn't work with the latest version of resque.

I've adapted your concept to work with the latest version.  I think this is a bit cleaner and doesn't rely on alias_method_chain and uses the plugin hooks (except for the little bit of instance_eval at the end..)

I've put this in my config/initializers:
https://gist.github.com/667942

Cheers,
Adam

**Comment by grosser** [comment]
Using after_fork hook to implement the feature is a nice idea.
staugaard is either ignoring the project or on a long holiday...
There are already some forks that do this, checking the network before rolling your own can save time :)

**Comment by adamcooper** [comment]
Thanks.

Is he not responding to pull requests? Is his fork still active?

I'm still getting used the network number not being in the Network tab as normally that would be one of the first things I do.  I didn't even realize there was a network around this plugin.  Definitely can save time.  At least it was a relatively short timeframe..

**Comment by grosser** [comment]
dont think he looks at pull requests or messages, maybe find his telefone and tell him to merge the pull request or else :>

**Comment by lantins** [comment]
Perhaps if we cause enough noise, he'll pull changes from one of the forks! ;-)

**Comment by staugaard** [comment]
Sorry guys, resque 1.10 is now supported.

Thanks for the noise :)

**Comment by lantins** [comment]
No no, thank you! =)
