### ISSUE TITLE
The child will fork a child and so on

### ISSUE THREAD

**Issue by next2you** [staugaard/resque-multi-job-forks#4]
Hi,

very nice plugin there. I've tried to track down a problem, where when plugin is enabled, the fork will happen in the child and the child will not exit. E.g. with time of 1 minutes per worker, I will see a fork happening initiallly, but then the next worker which is forked after 1 minute will have the child as parent process and the child will not exit.

Did you have any experiences with the side effecst, e.g. the stats are recorded per process and if breaking out the run loop it calls
unregister_worker (which will probably be a noop since the pid is not recorded any way).

Christian

**Comment by gravis** [comment]
Haven't searched enough yet, but we've tried this plugin yesterday, and it turned out to be real mess.
The servers went completely overloaded, swapping slowing to death. I wonder if we don't have exactly the same problem !
I will let you know

**Comment by gravis** [comment]
As said, the plugin if forking from the child, and will eat all memory available :

```
5025 ?        Ss     0:14 resque-1.10.0: Forked 5108 at 1293311340                                                          
5108 ?        S      0:00  \_ resque-1.10.0: Forked 5227 at 1293311401                                                          
5227 ?        S      0:00      \_ resque-1.10.0: Forked 5490 at 1293311461                                                          
5490 ?        S      0:00          \_ resque-1.10.0: Waiting for urgent,high,normal,mailer,low,maintenance       
```

**Comment by gravis** [comment]
(after 1 minute)

**Comment by next2you** [comment]
Yes, I think the problem is that the child should call exit at some point in the code so the controll will go to the parent process again.

I think best would be if resque would support getting a batch of events from the queue, e.g. max 100 events of X and then keep the rest as is. Our solution is currently to have $TESTING = true, which sets the @cant_fork variable to true and then run without the forking, not the best but better than having 100 forks a second :-)

**Comment by gravis** [comment]
sure :)

**Comment by staugaard** [comment]
What version on the gem are we talking about here. We've ben using the 0.2.0 version in very high load production for a long time without any problems.

**Comment by gravis** [comment]
sorry, I'm using  :

```
resque-multi-job-forks (0.3.0)
```

(haven't tried 0.2.0 yet)

**Comment by staugaard** [comment]
Hi I've asked @lantins to help you. He did the work on 0.3.0.

**Comment by gravis** [comment]
Thanks a lot, really appreciate !

**Comment by gravis** [comment]
Ok, found the issue, will send you a pull request in a few minutes

**Comment by staugaard** [comment]
Cool,

I've merged your fix, and released 0.3.1.

Thanks for your help,
Mick

**Comment by lantins** [comment]
Good catch gravis!

Luke

**Comment by gravis** [comment]
Be careful with my last fix, I'm not 100% sure.
I've deployed it in production, and I have :

```
0 of 0 Workers Working
```

But job are still performed (hopefully).
